export const GET_AUCTIONS = 'GET_AUCTIONS';
export const GET_AUCTIONS_SUCCESS = 'GET_AUCTIONS_SUCCESS';
export const GET_AUCTIONS_ERROR = 'GET_AUCTIONS_ERROR';

export const GET_AUCTION = 'GET_PRODUCT';
export const GET_AUCTION_SUCCESS = 'GET_AUCTION_SUCCESS';
export const GET_AUCTION_ERROR = 'GET_AUCTION_ERROR';

export const ADD_AUCTION = 'ADD_AUCTION';
export const ADD_AUCTION_SUCCESS = 'ADD_AUCTION_SUCCESS';
export const ADD_AUCTION_ERROR = 'ADD_AUCTION_ERROR';

export const DELETE_AUCTION = 'DELETE_AUCTION';
export const DELETE_AUCTION_SUCCESS = 'DELETE_AUCTION_SUCCESS';
export const DELETE_AUCTION_ERROR = 'DELETE_AUCTION_ERROR';

export const UPDATE_AUCTION = 'UPDATE_AUCTION';
export const UPDATE_AUCTION_SUCCESS = 'UPDATE_AUCTION_SUCCESS';
export const UPDATE_AUCTION_ERROR = 'UPDATE_AUCTION_ERROR';


export const GET_AUCTION_CATEGORY = 'GET_AUCTION_CATEGORY';
export const GET_AUCTION_CATEGORY_SUCCESS = 'GET_AUCTION_CATEGORY_SUCCESS';
export const GET_AUCTION_CATEGORY_ERROR = 'GET_AUCTION_CATEGORY_ERROR';

export const UPLOAD_AUCTION_IMAGE = 'UPLOAD_AUCTION_IMAGE';
export const UPLOAD_AUCTION_IMAGE_SUCCESS = 'UPLOAD_AUCTION_IMAGE_SUCCESS';
export const UPLOAD_AUCTION_IMAGE_ERROR = 'UPLOAD_AUCTION_IMAGE_ERROR';

